{
  mkDerivation,
  lib,
  fetchFromGitHub,
  aeson,
  amazonka,
  amazonka-core,
  amazonka-s3,
  ascii-progress,
  async,
  attoparsec,
  base,
  base64-bytestring,
  bytestring,
  cachix-api,
  concurrent-extra,
  conduit,
  conduit-concurrent-map,
  conduit-extra,
  conduit-zstd,
  containers,
  crypton,
  deepseq,
  dhall,
  directory,
  ed25519,
  either,
  exceptions,
  extra,
  filepath,
  fsnotify,
  generic-lens,
  hercules-ci-cnix-store,
  here,
  hnix-store-core,
  hnix-store-nar,
  http-client,
  http-client-tls,
  http-conduit,
  http-media,
  http-types,
  immortal,
  inline-c-cpp,
  katip,
  lukko,
  lzma-conduit,
  megaparsec,
  memory,
  microlens,
  netrc,
  network,
  nix-narinfo,
  optparse-applicative,
  pqueue,
  pretty-terminal,
  prettyprinter,
  process,
  protolude,
  resourcet,
  retry,
  safe-exceptions,
  servant,
  servant-auth,
  servant-auth-client,
  servant-client,
  servant-conduit,
  stm,
  stm-chans,
  stm-conduit,
  systemd,
  temporary,
  text,
  time,
  transformers,
  unix,
  unliftio,
  unliftio-core,
  unordered-containers,
  uri-bytestring,
  uuid,
  vector,
  versions,
  websockets,
  wuss,
  nix,
  typed-process,
}:
mkDerivation {
  pname = "cachix";
  version = "1.12.1";
  src = fetchFromGitHub {
    owner = "cachix";
    repo = "cachix";
    rev = "v1.12.1";
    hash = "sha256-OUB6hPlFBB9FRdZgZXSye4lDOg+fbrqKe8ePv2IM7NY=";
  };
  postUnpack = "sourceRoot=$sourceRoot/cachix";
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    aeson
    amazonka
    amazonka-core
    amazonka-s3
    ascii-progress
    async
    attoparsec
    base
    base64-bytestring
    bytestring
    cachix-api
    concurrent-extra
    conduit
    conduit-concurrent-map
    conduit-extra
    conduit-zstd
    containers
    crypton
    deepseq
    dhall
    directory
    ed25519
    either
    exceptions
    extra
    filepath
    fsnotify
    generic-lens
    hercules-ci-cnix-store
    here
    hnix-store-core
    hnix-store-nar
    http-client
    http-client-tls
    http-conduit
    http-media
    http-types
    immortal
    inline-c-cpp
    katip
    lukko
    lzma-conduit
    megaparsec
    memory
    microlens
    netrc
    network
    nix-narinfo
    optparse-applicative
    pqueue
    pretty-terminal
    prettyprinter
    process
    protolude
    resourcet
    retry
    safe-exceptions
    servant
    servant-auth
    servant-auth-client
    servant-client
    servant-conduit
    stm
    stm-chans
    stm-conduit
    systemd
    temporary
    text
    time
    transformers
    unix
    unliftio
    unliftio-core
    unordered-containers
    uri-bytestring
    uuid
    vector
    versions
    websockets
    wuss
  ];
  libraryPkgconfigDepends = [ nix ];
  executableHaskellDepends = [
    base
    safe-exceptions
    typed-process
  ];
  description = "Command-line client for Nix binary cache hosting https://cachix.org";
  license = lib.licenses.asl20;
  mainProgram = "cachix";
}
