#!/usr/bin/env python3
"""Generate top-level.nix from hackage-packages.nix.

Finds all executable Haskell packages with mainProgram set that are
non-broken, fully supported, and non-versioned, then generates a
top-level.nix that exposes each via justStaticExecutables.

All attribute names are normalized to lowercase kebab-case.
"""

import re
import sys
from pathlib import Path

BLOCKLIST = {
    "zip",
}

SCRIPT_DIR = Path(__file__).parent
REPO_DIR = SCRIPT_DIR.parent
HACKAGE_PACKAGES = REPO_DIR / "hackage-packages.nix"
PKGS_DIR = REPO_DIR / "pkgs"
TOP_LEVEL = REPO_DIR / "top-level.nix"


def normalize_name(name: str) -> str:
    # Lowercase and replace underscores with hyphens.
    # Haskell package names already use hyphens as separators,
    # so we just need to lowercase CamelCase names like ShellCheck -> shellcheck.
    return name.lower().replace("_", "-")


def parse_packages(content: str) -> list[tuple[str, str]]:
    """Parse hackage-packages.nix and return (attr_name, haskell_name) pairs."""
    blocks = re.split(r"\n  ([\w][\w_-]*) = callPackage\n", content)

    packages = []
    seen_kebab = {}
    i = 1
    while i < len(blocks) - 1:
        name = blocks[i]
        body = blocks[i + 1]
        i += 2

        # Skip versioned variants (e.g., pandoc_3_9_0_2)
        if re.search(r"_\d+(_\d+)*$", name):
            continue

        is_exec = "isExecutable = true;" in body
        is_broken = "broken = true;" in body
        hydra_none = "hydraPlatforms = lib.platforms.none;" in body
        has_main = "mainProgram" in body

        if not is_exec or is_broken or hydra_none or not has_main:
            continue

        kebab = normalize_name(name)

        if kebab in BLOCKLIST:
            continue

        # Handle collisions: first one wins
        if kebab in seen_kebab:
            continue

        seen_kebab[kebab] = name
        packages.append((kebab, name))

    packages.sort(key=lambda x: x[0])
    return packages


def generate_top_level(packages: list[tuple[str, str]]) -> str:
    lines = [
        "# This file is generated by scripts/generate-top-level.py — DO NOT EDIT MANUALLY.",
        "# Exposes haskell executables at the top-level pkgs scope with minimal closures.",
        "final: prev:",
        "let",
        "  justStaticExecutables = final.haskell.lib.compose.justStaticExecutables;",
        "  hp = final.haskellPackages;",
        "in",
        "{",
    ]

    for kebab, haskell_name in packages:
        lines.append(f"  {kebab} = justStaticExecutables hp.{haskell_name};")

    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def scan_custom_packages() -> list[tuple[str, str]]:
    """Scan pkgs/ for custom packages with mainProgram set."""
    packages = []
    if not PKGS_DIR.is_dir():
        return packages
    for pkg_dir in sorted(PKGS_DIR.iterdir()):
        default_nix = pkg_dir / "default.nix"
        if not default_nix.is_file():
            continue
        content = default_nix.read_text()
        if "mainProgram" in content:
            name = pkg_dir.name
            kebab = normalize_name(name)
            if kebab not in BLOCKLIST:
                packages.append((kebab, name))
    return packages


def main():
    content = HACKAGE_PACKAGES.read_text()
    packages = parse_packages(content)

    # Add custom packages from pkgs/, overriding hackage entries
    custom = scan_custom_packages()
    custom_kebabs = {k for k, _ in custom}
    packages = [(k, h) for k, h in packages if k not in custom_kebabs]
    packages.extend(custom)
    packages.sort(key=lambda x: x[0])

    output = generate_top_level(packages)
    TOP_LEVEL.write_text(output)
    print(f"Generated {TOP_LEVEL} with {len(packages)} entries.")


if __name__ == "__main__":
    main()
